# Generated by Django 4.1.3 on 2022-11-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_remove_women_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='car_id',
            field=models.BooleanField(default=True),
        ),
    ]
