# Generated by Django 4.1.3 on 2022-11-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_women_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat',
            new_name='categor',
        ),
    ]
