# Generated by Django 4.1.3 on 2022-11-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_rename_cat_women_categor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='categor',
        ),
    ]
