# Generated by Django 4.1.3 on 2022-11-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_alter_women_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='car_id',
            field=models.BooleanField(default=True),
        ),
    ]
