# Generated by Django 4.1.3 on 2022-11-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_women_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat',
            new_name='cat_id',
        ),
    ]
